#!/usr/bin/env python3
"""Run the production punctuation JNI probe inside the installed APK.

The probe APK is built without Gradle or copied production dependencies. Its
platform Instrumentation target loads ModelStore and TranscriptPostProcessor
from ``com.feelime.ime`` through the target class loader, then calls the real
punctuation model and native release methods.

Required environment variables:

* ``FEELIME_ADB_SERIAL``: the target device serial;
* ``FEELIME_VERIFY_APK``: the exact production APK expected on that device; and
* ``ANDROID_HOME`` (or ``ANDROID_SDK_ROOT``): an SDK used to build the probe.

``FEELIME_PUNCTUATION_EXPECTED_SOURCE`` is optional and accepts ``assets`` or
``downloaded``. The output directory defaults to
``~/tmp/feelime/punctuation-probe`` and may be changed with
``FEELIME_PUNCTUATION_PROBE_OUT``.
"""

import hashlib
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import device_verify as d


PROBE_PACKAGE = "com.feelime.punctuationprobe"
INSTRUMENTATION = PROBE_PACKAGE + "/.PunctuationInstrumentation"
CASE_NAMES = ("case_cn", "case_mixed_keep", "case_mixed_strip")
BUILD_SCRIPT = Path(__file__).resolve().parent / "punctuation-probe" / "build.sh"
RESULTS = []


class ProbeFailure(RuntimeError):
    """A prerequisite or instrumentation result did not satisfy the gate."""


def record(name, ok, detail=""):
    ok = bool(ok)
    RESULTS.append((name, ok, detail))
    print(("PASS " if ok else "FAIL ") + name +
          (f"  [{detail}]" if detail else ""), flush=True)


def sha256_file(path):
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def local_production_apk():
    raw = os.environ.get("FEELIME_VERIFY_APK", "").strip()
    if not raw:
        raise ProbeFailure("FEELIME_VERIFY_APK is required")
    path = Path(raw).expanduser()
    if not path.is_file() or path.stat().st_size == 0:
        raise ProbeFailure(f"FEELIME_VERIFY_APK is not a non-empty file: {path}")
    return path


def shell_quote(value):
    # Device package paths are generated by Android, but quote them before
    # passing them to the shell to keep this helper safe across OEM paths.
    return "'" + str(value).replace("'", "'\\''") + "'"


def installed_production_sha():
    output = d.shell("pm path com.feelime.ime", timeout=30)
    paths = [line.removeprefix("package:").strip()
             for line in output.splitlines() if line.startswith("package:")]
    if not paths:
        raise ProbeFailure("production package com.feelime.ime is not installed")
    base = next((path for path in paths if path.endswith("/base.apk")), paths[0])
    remote = d.shell("sha256sum " + shell_quote(base), timeout=60)
    match = re.search(r"\b([0-9a-fA-F]{64})\b", remote)
    if not match:
        raise ProbeFailure("device could not report the production APK SHA-256")
    return base, match.group(1).lower()


def build_probe(production_apk):
    output = Path(os.environ.get(
        "FEELIME_PUNCTUATION_PROBE_OUT",
        str(Path.home() / "tmp" / "feelime-0175" / "punctuation-probe"),
    )).expanduser()
    output.mkdir(parents=True, exist_ok=True)
    environment = os.environ.copy()
    environment["FEELIME_PUNCTUATION_PROBE_OUT"] = str(output)
    # The build script performs a signer comparison against this same
    # production APK when FEELIME_VERIFY_APK is present.
    environment["FEELIME_VERIFY_APK"] = str(production_apk)
    timeout = float(os.environ.get("FEELIME_PUNCTUATION_BUILD_TIMEOUT_S", "180"))
    try:
        completed = subprocess.run(
            [str(BUILD_SCRIPT)],
            cwd=str(BUILD_SCRIPT.parent),
            env=environment,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
    except (OSError, subprocess.TimeoutExpired) as error:
        raise ProbeFailure(f"punctuation probe build failed: {error}") from error
    if completed.stdout:
        print(completed.stdout, end="", flush=True)
    if completed.stderr:
        print(completed.stderr, end="", file=sys.stderr, flush=True)
    if completed.returncode != 0:
        raise ProbeFailure(
            f"punctuation probe build exited {completed.returncode}"
        )
    apk = output / "punctuation-probe-debug.apk"
    if not apk.is_file() or apk.stat().st_size == 0:
        raise ProbeFailure(f"build did not produce {apk}")
    return apk


def adb_checked(*args, timeout=120):
    adb = shutil.which("adb") or "adb"
    command = [adb, "-s", d.SERIAL, *map(str, args)]
    try:
        completed = subprocess.run(
            command, capture_output=True, text=True, timeout=timeout
        )
    except (OSError, subprocess.TimeoutExpired) as error:
        raise ProbeFailure(f"adb {' '.join(command[2:])} failed: {error}") from error
    if completed.returncode != 0:
        detail = (completed.stderr or completed.stdout).strip().replace("\n", " ")
        raise ProbeFailure(
            f"adb {' '.join(command[2:])} exited {completed.returncode}: {detail}"
        )
    # adb normally prints instrumentation results on stdout. Keep stderr too
    # because platform builds occasionally route runner diagnostics there;
    # parsing both still leaves the explicit INSTRUMENTATION_CODE authoritative.
    return (completed.stdout or "") + (completed.stderr or "")


def install_probe(apk):
    output = adb_checked("install", "-r", str(apk), timeout=180)
    if "success" not in output.lower():
        raise ProbeFailure(f"probe installation returned unexpected output: {output.strip()}")


def run_instrumentation():
    command = ["shell", "am", "instrument", "-w", "-r"]
    expected = os.environ.get("FEELIME_PUNCTUATION_EXPECTED_SOURCE", "").strip()
    if expected:
        command += ["-e", "expected_source", expected]
    command.append(INSTRUMENTATION)
    return adb_checked(*command, timeout=float(
        os.environ.get("FEELIME_PUNCTUATION_TIMEOUT_S", "300")
    ))


def parse_instrumentation(output):
    values = {}
    codes = []
    for raw_line in output.splitlines():
        line = raw_line.strip()
        if line.startswith("INSTRUMENTATION_RESULT:"):
            payload = line.split(":", 1)[1].strip()
            if "=" in payload:
                key, value = payload.split("=", 1)
                values[key.strip()] = value
        match = re.match(r"INSTRUMENTATION_CODE:\s*(-?\d+)", line)
        if match:
            codes.append(int(match.group(1)))
    return values, codes


def print_case_results(values):
    for name in CASE_NAMES:
        input_value = values.get(name + "_input", "<missing>")
        output_value = values.get(name + "_output", "<missing>")
        pass_value = values.get(name + "_pass", "false")
        print(
            f"CASE {name}: input={input_value!r} output={output_value!r} "
            f"pass={pass_value}",
            flush=True,
        )


def main():
    try:
        production = local_production_apk()
        local_digest = sha256_file(production)
        record("production APK exists", True,
               f"sha256={local_digest}")

        device_path, device_digest = installed_production_sha()
        matches = local_digest == device_digest
        record("installed production APK matches FEELIME_VERIFY_APK", matches,
               f"device={device_path} local={local_digest} device={device_digest}")
        if not matches:
            raise ProbeFailure("production APK SHA-256 mismatch")

        probe = build_probe(production)
        record("instrumentation APK built and debug-signed", True,
               f"path={probe} sha256={sha256_file(probe)}")
        install_probe(probe)
        record("instrumentation APK installed", True, PROBE_PACKAGE)

        raw_output = run_instrumentation()
        values, codes = parse_instrumentation(raw_output)
        print_case_results(values)
        if not codes:
            record("instrumentation finished with code 0", False,
                   "INSTRUMENTATION_CODE missing")
        else:
            record("instrumentation finished with code 0", codes[-1] == 0,
                   f"code={codes[-1]}")
        all_pass = values.get("all_pass", "").lower() == "true"
        record("production punctuation runner reports all cases pass", all_pass,
               values.get("failure", ""))
        for name in CASE_NAMES:
            record(name + " result", values.get(name + "_pass", "false").lower() == "true",
                   values.get(name + "_output", "<missing>"))
        record("feelime_asr preference restored",
               values.get("preference_restored", "false").lower() == "true")
        record("production classes released",
               values.get("post_processor_released", "false").lower() == "true"
               and values.get("model_store_released", "false").lower() == "true")
    except ProbeFailure as error:
        record("punctuation probe prerequisites", False, str(error))
    except Exception as error:
        record("punctuation probe prerequisites", False, str(error))

    failed = [name for name, ok, _ in RESULTS if not ok]
    if failed:
        print("punctuation probe failed: " + ", ".join(failed), file=sys.stderr)
        return 1
    print("punctuation probe: all checks passed", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
