#!/usr/bin/env python3
"""Generate engine-data/rime/stroke.dict.yaml (issue #18 笔画输入法) from
the pinned upstream rime-stroke dictionary + the rime-essay word-frequency
table.

裁剪与派生规则（design: docs/design/keyboard.md §7 / 方案 v1）：
- 字集白名单：GB2312 全集（简体字形；上游是 CNS11643 超集，17 万条里
  绝大多数是生僻字）。
- 权重：essay.txt 单字频次按 opencc TSCharacters.txt 繁→简聚合同字
  （essay 以繁体统计——「说」原频 0、「說」340k，直查会让 2047 个
  简体常用字塌成零频；聚合后同字取 max）。仍缺的字（实测仅 2 个
  生僻字）回落权重 1。use_preset_vocabulary=false，部署自包含。
- 单通配派生：每条码（长度 ≤ WILDCARD_MAX_LEN）派生「第 i 笔 → *」
  变体，以 (字, 码) 为键去重；通配行权重 = 原权重 // WILDCARD_WEIGHT_
  DIV。注意排序契约（实测）：completion 的迭代序含「剩余码长度」维度，
  通配行不保证严格按字频排在精确行后——见方案文档「已知边界」。

用法：
  generate-stroke-dict.py [--check]
  输入路径用环境变量或默认值：
    FEELIME_STROKE_SRC   上游 stroke.dict.yaml（rime-stroke@1e8fff9）
    FEELIME_ESSAY_TXT    rime-essay essay.txt（e9b1a37）
"""
import argparse
import os
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
DST = ROOT / 'app/src/main/assets/engine-data/rime/stroke.dict.yaml'
DEFAULT_SRC = pathlib.Path.home() / 'tmp/rime-stroke-probe/stroke.dict.yaml'
DEFAULT_ESSAY = pathlib.Path.home() / 'tmp/stroke-build/work/essay.txt'
T2S = ROOT / 'app/src/main/assets/engine-data/rime/opencc/TSCharacters.txt'

MAX_CODE_LEN = 48
WILDCARD_MAX_LEN = 20
WILDCARD_WEIGHT_DIV = 1000
HEADER = """# Generated by scripts/generate-stroke-dict.py from rime-stroke@1e8fff9
# (upstream https://github.com/rime/rime-stroke, CNS11643-derived) pruned to
# the GB2312 charset with rime-essay@e9b1a37 single-character frequencies as
# weights, plus single-wildcard (*) derived rows. Do not edit by hand.
---
name: stroke
version: "1.0"
sort: by_weight
use_preset_vocabulary: false
max_phrase_length: 1
...
"""


def gb2312_chars():
    out = set()
    for hi in range(0xB0, 0xF8):
        for lo in range(0xA1, 0xFF):
            try:
                out.add(bytes([hi, lo]).decode('gb2312'))
            except UnicodeDecodeError:
                pass
    return out


def essay_frequencies(essay_path, t2s_path):
    """essay 单字频次，繁→简聚合同字取 max（见模块 docstring）。"""
    t2s = {}
    for line in t2s_path.read_text(encoding='utf-8').splitlines():
        if line.startswith('#') or '\t' not in line:
            continue
        key, _, values = line.partition('\t')
        simplified = values.split(' ')[0]
        if len(key) == 1 and len(simplified) == 1:
            t2s[key] = simplified
    freq = {}

    def bump(char, value):
        if value > freq.get(char, 0):
            freq[char] = value

    for line in essay_path.read_text(encoding='utf-8').splitlines():
        parts = line.split('\t')
        if len(parts) == 2 and len(parts[0]) == 1:
            try:
                value = int(parts[1])
            except ValueError:
                continue
            char = parts[0]
            bump(char, value)
            if char in t2s:
                bump(t2s[char], value)
    return freq


def parse_upstream(path):
    entries = []
    for line in path.read_text(encoding='utf-8').splitlines():
        if line.startswith('#') or not line.strip():
            continue
        parts = line.split('\t')
        if len(parts) >= 2 and re.fullmatch(r'[hspnz]+', parts[1] or ''):
            entries.append((parts[0], parts[1]))
    return entries


def build_rows(src, essay):
    gb = gb2312_chars()
    exact = [(text, code) for text, code in parse_upstream(src) if text in gb]
    rows = []
    seen_wild = set()
    for text, code in exact:
        weight = essay.get(text, 1)
        rows.append((text, code, weight))
        if len(code) > WILDCARD_MAX_LEN:
            continue
        wild_weight = max(weight // WILDCARD_WEIGHT_DIV, 1)
        for i in range(len(code)):
            variant = code[:i] + '*' + code[i + 1:]
            key = (text, variant)
            if key in seen_wild:
                continue
            seen_wild.add(key)
            rows.append((text, variant, wild_weight))
    rows.sort(key=lambda r: (-r[2], r[1], r[0]))
    return rows, exact


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    # 构建脚本（build-cmake-native-engines.sh）把派生词典生成进 work 目录
    # 自包含编译；缺省仍写仓库资产路径（人工再生成用）。
    parser.add_argument('--output', type=pathlib.Path, default=DST)
    parser.add_argument('--src', type=pathlib.Path,
                        default=pathlib.Path(os.environ.get('FEELIME_STROKE_SRC', DEFAULT_SRC)))
    parser.add_argument('--essay', type=pathlib.Path,
                        default=pathlib.Path(os.environ.get('FEELIME_ESSAY_TXT', DEFAULT_ESSAY)))
    args = parser.parse_args()
    src = args.src
    essay_path = args.essay
    freq = essay_frequencies(essay_path, T2S)
    rows, exact = build_rows(src, freq)
    body = ''.join(f'{text}\t{code}\t{weight}\n' for text, code, weight in rows)
    zero = sum(1 for text, _ in exact if text not in freq)
    top = max(exact, key=lambda e: freq.get(e[0], 1))
    print(f'exact rows: {len(exact)}  wildcard rows: {len(rows) - len(exact)}  '
          f'total: {len(rows)}  bytes: {len(body.encode())}')
    print(f'essay-uncovered chars (weight=1): {zero}  top char: {top[0]}({freq.get(top[0], 1)})')
    if args.check:
        if not DST.is_file():
            raise SystemExit('stroke.dict.yaml missing - run generate-stroke-dict.py')
        if DST.read_text(encoding='utf-8') != HEADER + body:
            raise SystemExit('stroke.dict.yaml differs - run generate-stroke-dict.py')
        print('stroke.dict.yaml matches the pruned derivation.')
        return
    args.output.write_text(HEADER + body, encoding='utf-8')
    print(f'written: {args.output}')


if __name__ == '__main__':
    sys.exit(main())
